
# 🧮 NumPy Mega Homework (60+ Tasks)

This workbook contains **lots** of NumPy practice tasks, grouped by topic.  
For each task, write your solution in the empty code cell that follows it.

**Rules**
- Use **NumPy** (`import numpy as np`) for array operations.
- Do **not** use Python lists for computations unless explicitly asked.
- Add comments to explain key steps.

**Sections**
1. Array Basics & Creation (10 tasks)  
2. Indexing & Slicing (8 tasks)  
3. Array Operations & Broadcasting (8 tasks)  
4. Mathematical Functions (6 tasks)  
5. Aggregations & Descriptive Stats (6 tasks)  
6. Random Numbers & Simulations (8 tasks)  
7. Linear Algebra (6 tasks)  
8. Reshaping, Stacking & Splitting (5 tasks)  
9. Real‑World Mini Case Studies (7 tasks)


## 1) Array Basics & Creation

**1.1** Import NumPy as `np` and print the installed version.

In [1]:
import numpy as np

**1.2** Create a 1D array with values from 0 to 20 (inclusive).

In [2]:
# Using arange
arr = np.arange(0, 21)  # 0 to 20 inclusive
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


**1.3** Create a 1D array of the first 15 even numbers.

In [208]:
# First 15 even numbers
even_numbers = np.arange(2, 31, 2)
print(even_numbers)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


**1.4** Create a 3×3 array filled with 7s (use `np.full`).

In [209]:
arr1 = np.full((3, 3), 7)
print(arr1)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


**1.5** Create a 5×5 identity matrix.

In [210]:
# Using np.eye
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**1.6** Create an array of 10 numbers linearly spaced between 0 and 1 (inclusive).

In [212]:
arr2 = np.linspace(0, 1, 10)  # 10 numbers from 0 to 1 inclusive
print(arr2)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


**1.7** Create an array of 12 values logarithmically spaced between 10^0 and 10^3.

In [3]:
# 12 values from 10^0 to 10^3
arr5 = np.logspace(0, 3, 12)
print(arr5)


[   1.            1.87381742    3.51119173    6.57933225   12.32846739
   23.101297     43.28761281   81.11308308  151.9911083   284.80358684
  533.66992312 1000.        ]


**1.8** Create a boolean array of length 12 that alternates `True, False, True, False, ...`.

In [2]:
# repeat pattern 6 times
arr6=np.tile([True,False],6)
print(arr6)

[ True False  True False  True False  True False  True False  True False]


**1.9** Create a 4×4 array of random integers from 10 to 99 (inclusive).

In [4]:
arr7=np.random.randint(10,100,(4,4))
print(arr7)

[[26 34 69 55]
 [65 86 29 24]
 [54 48 55 80]
 [85 60 62 68]]


**1.10** Given `a = np.array([1, 2, 3], dtype=np.int32)`, change its dtype to float64 without copying if possible.

In [9]:
a=np.array([1, 2, 3])
arr8A=np.float64(a)                        #version1

arr8B=a.astype(np.float64,copy=False)      #version2

arr8A.dtype                                
arr8B.dtype

dtype('float64')

## 2) Indexing & Slicing

**2.1** Create an array `x = np.arange(1, 26).reshape(5,5)`. Extract the **center 3×3 block**.

In [5]:
x=np.arange(1,26).reshape(5,5)        
result=x[1:4,1:4]                       # 1:4 for rows selects rows 1, 2, 3
                                    # 1:4 for columns selects columns 1, 2, 3
print(result)                 

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


**2.2** From `x` above, extract the **border elements** (top row, bottom row, leftmost column, rightmost column) into a 1D array.

In [11]:
top=x[0,:]
bottom=x[-1,:]
left=x[1:-1,0] #Left column-excluding top and bottom, because they are already included
right=x[1:-1,-1]  #Right column-excluding top and bottom

border=np.concatenate([top,bottom,left,right],axis=0)
print(border)

[ 1  2  3  4  5 21 22 23 24 25  6 11 16 10 15 20]


**2.3** From `x`, select every other row and every other column.

In [9]:
others=x[::2,::2]
print(others)

[[ 1  3  5]
 [11 13 15]
 [21 23 25]]


**2.4** Given `y = np.arange(10)`, reverse it using slicing only.

In [10]:
y = np.arange(10)

reversed_y=y[::-1]
print(reversed_y)

[9 8 7 6 5 4 3 2 1 0]


**2.5** From `y`, extract elements with **odd indices** (1,3,5,...) using slicing.

In [11]:
odd_y=y[1::2]

print(odd_y)


[1 3 5 7 9]


**2.6** Use **fancy indexing** to pick elements at indices `[0, 3, 7]` from `y`.

In [16]:
fancy_y=y[[0,3,7]]   #Here we use a list of indices [0, 3, 7] to directly pick specific
                         #elements from 'y'.
print(fancy_y)     

[0 3 7]


**2.7** Given `z = np.array([3, -1, 7, 0, -5, 2])`, replace **negative** values with `0` using boolean indexing.

In [17]:
z = np.array([3, -1, 7, 0, -5, 2])

negatives=z<0  
# We create a boolean negatives (z < 0) that identifies all negative values in 'z'.
# Using this, we directly replace the negative values with 0.

z[negatives]=0
print(z)

[3 0 7 0 0 2]


**2.8** Given `M = np.arange(1,17).reshape(4,4)`, set the **diagonal** to `-1` without a loop.

In [37]:
M = np.arange(1,17).reshape(4,4)

diagonal=np.fill_diagonal(M,-1) #np.fill_diagonal(M, -1) directly replaces all diagonal values with -1.
print(diagonal)

None


## 3) Array Operations & Broadcasting

**3.1** Compute element‑wise addition, subtraction, multiplication, and division of arrays `a=[1,2,3,4]` and `b=[10,20,30,40]`.

In [12]:
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])

add=a+b
sub=a-b
mul=a*b
div=a/b

print("Addition:     ", add)
print("Subtraction:  ", sub)
print("Multiplication:", mul)
print("Division:     ", div)

Addition:      [11 22 33 44]
Subtraction:   [ -9 -18 -27 -36]
Multiplication: [ 10  40  90 160]
Division:      [0.1 0.1 0.1 0.1]


**3.2** Square all elements of `a` without using a Python loop.

In [62]:
Square=np.square(a)
print(Square)

[ 1  4  9 16]


**3.3** Let `A = np.ones((3,3))` and `v = np.array([1,2,3])`. Add `v` to each **row** of `A` using broadcasting.

In [70]:
A = np.ones((3,3))              # A =[[1. 1. 1.]
                                #     [1. 1. 1.]
                                #     [1. 1. 1.]]
        
v = np.array([1,2,3])           # v=[1 2 3]

Add=A+v
print(Add)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


**3.4** Multiply each **column** of `A` by `[1,2,3]` using broadcasting.

In [72]:
Multiple=A*[1,2,3]              # A =[[1. 1. 1.]
                                #     [1. 1. 1.]
                                #     [1. 1. 1.]]
        

print(Multiple)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


**3.5** Normalize array `p = np.array([3.0, 4.0, 0.0, 8.0])` to unit length (divide by its Euclidean norm).

In [75]:
p = np.array([3.0, 4.0, 0.0, 8.0])
norm = np.linalg.norm(p)     #Compute the Euclidean norm (vector length) 

p_normalized = p / norm      #Divide each component of the vector by this norm.

print(p_normalized)


[0.31799936 0.42399915 0.         0.8479983 ]


**3.6** Compute the pairwise sum of vectors in `X = np.array([[1,2],[3,4],[5,6]])` with `y = np.array([10,20])` via broadcasting (result shape 3×2).

In [78]:
X = np.array([[1,2],[3,4],[5,6]])
y = np.array([10,20])

print(X+y)

[[11 22]
 [13 24]
 [15 26]]


**3.7** Given `B = np.arange(12).reshape(3,4)`, subtract the **column means** from each column (column‑wise centering) using broadcasting.

In [98]:
B = np.arange(12).reshape(3,4)
col_means = np.mean(B, axis=0)   #Compute the mean of each column (axis=0 means column-wise)
B_centered = B - col_means       # Subtract the column means from each column using broadcasting
                                 # this operation centers each column around zero
print(B_centered)


[[-4. -4. -4. -4.]
 [ 0.  0.  0.  0.]
 [ 4.  4.  4.  4.]]


**3.8** Clip array values: given `w = np.array([-3, -1, 0, 2, 9])`, clip to the range `[0, 5]`.

In [103]:
w = np.array([-3, -1, 0, 2, 9])  # Values less than 0 are set to 0.
                                    #Values greater than 5 are set to 5.
                                        #Values within [0, 5] remain unchanged.
np.clip(w,0,5)

array([0, 0, 0, 2, 5])

## 4) Mathematical Functions

**4.1** For `q = np.linspace(-2*np.pi, 2*np.pi, 50)`, compute `sin(q)`, `cos(q)`, and `tan(q)` arrays.

In [13]:
q = np.linspace(-2*np.pi, 2*np.pi, 50)
sin_q=np.sin(q)
cos_q=np.cos(q)
tan_q=np.tan(q)

print("sin(q):", sin_q)
print("cos(q):", cos_q)
print("tan(q):", tan_q)

sin(q): [ 2.44929360e-16  2.53654584e-01  4.90717552e-01  6.95682551e-01
  8.55142763e-01  9.58667853e-01  9.99486216e-01  9.74927912e-01
  8.86599306e-01  7.40277997e-01  5.45534901e-01  3.15108218e-01
  6.40702200e-02 -1.91158629e-01 -4.33883739e-01 -6.48228395e-01
 -8.20172255e-01 -9.38468422e-01 -9.95379113e-01 -9.87181783e-01
 -9.14412623e-01 -7.81831482e-01 -5.98110530e-01 -3.75267005e-01
 -1.27877162e-01  1.27877162e-01  3.75267005e-01  5.98110530e-01
  7.81831482e-01  9.14412623e-01  9.87181783e-01  9.95379113e-01
  9.38468422e-01  8.20172255e-01  6.48228395e-01  4.33883739e-01
  1.91158629e-01 -6.40702200e-02 -3.15108218e-01 -5.45534901e-01
 -7.40277997e-01 -8.86599306e-01 -9.74927912e-01 -9.99486216e-01
 -9.58667853e-01 -8.55142763e-01 -6.95682551e-01 -4.90717552e-01
 -2.53654584e-01 -2.44929360e-16]
cos(q): [ 1.          0.96729486  0.8713187   0.71834935  0.51839257  0.28452759
  0.03205158 -0.22252093 -0.46253829 -0.67230089 -0.8380881  -0.94905575
 -0.99794539 -0.98155916

**4.2** Compute element‑wise `exp`, `log`, and `sqrt` for `r = np.array([1, e, e**2, 10.0])` (use `np.e` where needed).

In [15]:
r = np.array([1, np.e, np.e**2, 10.0])

# Element-wise exponential
r_exp = np.exp(r)

# Element-wise natural logarithm
r_log = np.log(r)

# Element-wise square root
r_sqrt = np.sqrt(r)

print(r)
print("exp:", r_exp)
print("log:", r_log)
print("sqrt:", r_sqrt)


[ 1.          2.71828183  7.3890561  10.        ]
exp: [2.71828183e+00 1.51542622e+01 1.61817799e+03 2.20264658e+04]
log: [0.         1.         2.         2.30258509]
sqrt: [1.         1.64872127 2.71828183 3.16227766]


**4.3** Compute `np.floor`, `np.ceil`, and `np.round` for `s = np.array([1.2, 3.7, -2.3, -4.8])`.

In [126]:
s = np.array([1.2, 3.7, -2.3, -4.8])
floor_s=np.floor(s)
ceil_s=np.ceil(s)
round_s=np.round(s)

print("floor:", floor_s)
print("ceil:", ceil_s)
print("round:", round_s)


floor: [ 1.  3. -3. -5.]
ceil: [ 2.  4. -2. -4.]
round: [ 1.  4. -2. -5.]


**4.4** Safely compute `log1p(x)` for `x = np.array([0, 1e-10, 1e-5, 0.1])`. Why is `log1p` preferred here? (Answer in a comment)

In [128]:
x = np.array([0, 1e-10, 1e-5, 0.1])       

# np.log1p(x) computes log(1 + x) in a numerically stable way.
# For very small x, directly computing np.log(1 + x) can lose precision due to floating-point rounding errors.
# Using log1p ensures accurate results even for tiny x values.
log_values = np.log1p(x)

print(log_values)

[0.00000000e+00 1.00000000e-10 9.99995000e-06 9.53101798e-02]


**4.5** Compute the sigmoid function `σ(x) = 1 / (1 + exp(-x))` for `x = np.linspace(-8, 8, 9)`.

In [16]:
x = np.linspace(-8, 8, 9)

sigmoid = 1 / (1 + np.exp(-x))
print(sigmoid)


[3.35350130e-04 2.47262316e-03 1.79862100e-02 1.19202922e-01
 5.00000000e-01 8.80797078e-01 9.82013790e-01 9.97527377e-01
 9.99664650e-01]


**4.6** Standardize `t` (z‑score): given `t = np.array([10, 12, 9, 13, 11, 8])`, transform to mean 0 and std 1.

In [18]:
import numpy as np

t = np.array([10, 12, 9, 13, 11, 8])

# Definition: z-score = (x - mean) / std
z = (t - t.mean()) / t.std()

print("Standardized t (z-score):", z)


Standardized t (z-score): [-0.29277002  0.87831007 -0.87831007  1.46385011  0.29277002 -1.46385011]


## 5) Aggregations & Descriptive Stats

**5.1** Given `u = np.array([5, 5, 9, 1, 1, 9, 9])`, compute: mean, median, variance, std, min, max.

In [147]:
u = np.array([5, 5, 9, 1, 1, 9, 9])
mean_u=np.mean(u)
median_u=np.median(u)
var_u=np.var(u)
std_u=np.std(u)
min_u=np.min(u)
max_u=np.max(u)

print('mean is:', mean_u, 
      'median is:', median_u, 
      'variance is:', var_u, 
      'standard deviation is:', std_u, 
      'minimum is:', min_u, 
      'maximum is:', max_u)


mean is: 5.571428571428571 median is: 5.0 variance is: 11.10204081632653 standard deviation is: 3.3319725113401715 minimum is: 1 maximum is: 9


**5.2** Compute `argmin` and `argmax` for `u`. What values do they point to? (Print index & value)

In [148]:
u = np.array([5, 5, 9, 1, 1, 9, 9])

# Find indices of min and max
argmin_u = np.argmin(u)
argmax_u = np.argmax(u)

print("argmin index:", argmin_u, "value:", u[argmin_u])
print("argmax index:", argmax_u, "value:", u[argmax_u])


argmin index: 3 value: 1
argmax index: 2 value: 9


**5.3** For `V = np.arange(12).reshape(3,4)`, compute **row sums** and **column means**.

In [149]:
V = np.arange(12).reshape(3,4)

# Row sums (sum along axis=1)
row_sums = np.sum(V, axis=1)

# Column means (mean along axis=0)
col_means = np.mean(V, axis=0)

print("Matrix V:\n", V)
print("Row sums:", row_sums)
print("Column means:", col_means)

Matrix V:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Row sums: [ 6 22 38]
Column means: [4. 5. 6. 7.]


**5.4** For `V`, compute the cumulative sum along axis 1 and the cumulative product along axis 0.

In [150]:
V = np.arange(12).reshape(3,4)

# Cumulative sum along axis=1 (row-wise cumulative sum)
cumsum_axis1 = np.cumsum(V, axis=1)

# Cumulative product along axis=0 (column-wise cumulative product)
cumprod_axis0 = np.cumprod(V, axis=0)

print("Matrix V:\n", V)
print("Cumulative sum along axis 1:\n", cumsum_axis1)
print("Cumulative product along axis 0:\n", cumprod_axis0)


Matrix V:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Cumulative sum along axis 1:
 [[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]
Cumulative product along axis 0:
 [[  0   1   2   3]
 [  0   5  12  21]
 [  0  45 120 231]]


**5.5** For `u`, return the **unique** values and their **counts** (hint: `np.unique(..., return_counts=True)`).

In [158]:
u = np.array([5, 5, 9, 1, 1, 9, 9])

# Find unique values and their counts
unique_vals, counts = np.unique(u, return_counts=True)

print("Unique values:", unique_vals)
print("Counts:", counts)


Unique values: [1 5 9]
Counts: [2 2 3]


**5.6** Compute the **50th percentile (median)** and **90th percentile** of `u` using `np.percentile`.

In [159]:
u = np.array([5, 5, 9, 1, 1, 9, 9])

# 50th percentile (median) və 90th percentile
p50 = np.percentile(u, 50)   # median
p90 = np.percentile(u, 90)

print("50th percentile (median):", p50)
print("90th percentile:", p90)


50th percentile (median): 5.0
90th percentile: 9.0


## 6) Random Numbers & Simulations

**6.1** Set a random seed (e.g., 123). Generate 10 random numbers from the uniform distribution [0,1).

In [160]:
# Set random seed
np.random.seed(123)

# Generate 10 random numbers from uniform [0, 1)
rand_nums = np.random.rand(10)

print(rand_nums)


[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646
 0.9807642  0.68482974 0.4809319  0.39211752]


**6.2** Generate a 3×3 matrix of random integers between 1 and 100 (inclusive).

In [164]:
# Generate 3x3 matrix of random integers between 1 and 100 (inclusive)
matrix = np.random.randint(1, 101, size=(3,3))

print(matrix)


[[28 35 98]
 [77 41  4]
 [70 65 76]]


**6.3** Draw 1,000 samples from a standard normal distribution and compute sample mean and std. Compare to theoretical values.

In [168]:
# 1,000 samples from standard normal distribution
samples = np.random.randn(1000)

# Sample mean and standard deviation
sample_mean = np.mean(samples)
sample_std = np.std(samples)

print("Sample mean:", sample_mean)
print("Sample std:", sample_std)
print("Theoretical mean: 0, Theoretical std: 1")

#Sample mean and std are close to theoretical values (0 and 1) but not exact due to randomness.
#Increasing the number of samples (e.g., 10,000) will make the sample statistics closer to the theoretical values.

Sample mean: 0.06463548843744757
Sample std: 0.9831741829559825
Theoretical mean: 0, Theoretical std: 1


**6.4** Simulate 1,000 fair coin flips (use 0/1). Estimate the probability of heads.

In [170]:
# Set random seed
np.random.seed(123)

# Simulate 1,000 fair coin flips (0 = tails, 1 = heads)
flips = np.random.randint(0, 2, size=1000)

# Estimate probability of heads
prob_heads = np.mean(flips)  # mean = fraction of 1s (heads)

print("Estimated probability of heads:", prob_heads)


Estimated probability of heads: 0.52


**6.5** Simulate rolling two fair dice 10,000 times. Estimate the probability that the sum equals 7.

In [173]:
# Set random seed for reproducibility
np.random.seed(123)

# Simulate 10,000 rolls for two dice
dice1 = np.random.randint(1, 7, size=10000)
dice2 = np.random.randint(1, 7, size=10000)

# Sum of the two dice
sums = dice1 + dice2

# Estimate probability that sum equals 7
prob_sum_7 = np.mean(sums == 7)  # fraction of times sum is 7

print("Estimated probability that sum = 7:", prob_sum_7)


Estimated probability that sum = 7: 0.1677


**6.6** Draw 500 samples from a binomial distribution (n=20, p=0.4). Compute mean and variance; compare to theory.

In [175]:
# Set random seed 
np.random.seed(123)

# Draw 500 samples from Binomial(n=20, p=0.4)
n, p = 20, 0.4
samples = np.random.binomial(n, p, size=500)

# Compute sample mean and variance
sample_mean = np.mean(samples)
sample_var = np.var(samples)

# Theoretical mean and variance
theoretical_mean = n * p
theoretical_var = n * p * (1 - p)

print("Sample mean:", sample_mean)
print("Sample variance:", sample_var)
print("Theoretical mean:", theoretical_mean)
print("Theoretical variance:", theoretical_var)


Sample mean: 7.944
Sample variance: 4.9328639999999995
Theoretical mean: 8.0
Theoretical variance: 4.8


**6.7** Use `np.random.multivariate_normal` to draw 1,000 2D samples with mean `[0,0]` and covariance `[[1,0.5],[0.5,1]]`. Compute the sample covariance matrix.

In [176]:
# Set random seed  
np.random.seed(123)

# Define mean and covariance
mean = [0, 0]
cov = [[1, 0.5],
       [0.5, 1]]

# Draw 1,000 2D samples
samples = np.random.multivariate_normal(mean, cov, size=1000)

# Compute sample covariance matrix
sample_cov = np.cov(samples, rowvar=False)  # rowvar=False: each column is a variable

print("Sample covariance matrix:\n", sample_cov)


Sample covariance matrix:
 [[0.98010969 0.50207627]
 [0.50207627 0.96368557]]


**6.8** Monte Carlo: Estimate π by randomly sampling 100,000 points in the unit square and counting how many fall inside the unit quarter‑circle.

In [177]:
# Set random seed for reproducibility
np.random.seed(123)

# Number of random points
N = 100000

# Sample x and y coordinates uniformly in [0,1)
x = np.random.rand(N)
y = np.random.rand(N)

# Count points inside the quarter-circle (radius=1)
inside_circle = (x**2 + y**2) <= 1
num_inside = np.sum(inside_circle)

# Estimate π
pi_estimate = 4 * num_inside / N

print("Estimated π:", pi_estimate)


Estimated π: 3.13496


## 7) Linear Algebra

**7.1** Compute the dot product of `a = [1,2,3]` and `b = [4,5,6]`.

In [178]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

#Element-wise multiply: [1*4, 2*5, 3*6] = [4, 10, 18]
#Sum: 4 + 10 + 18 = 32 --> dot product.
dot_product = np.dot(a, b)

print("Dot product:", dot_product)


Dot product: 32


**7.2** Given `A = [[2,1],[1,2]]`, compute determinant, inverse, and verify `A @ A_inv ≈ I`.

In [180]:
# Define matrix
A = np.array([[2, 1],
              [1, 2]])

# Compute determinant
det_A = np.linalg.det(A)

# Compute inverse
A_inv = np.linalg.inv(A)

# Verify A @ A_inv ≈ Identity matrix
identity_check = A @ A_inv

print("Determinant of A:", det_A)
print("Inverse of A:\n", A_inv)
print("A @ A_inv:\n", identity_check)


Determinant of A: 2.9999999999999996
Inverse of A:
 [[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]
A @ A_inv:
 [[1. 0.]
 [0. 1.]]


**7.3** For `A` above, compute eigenvalues and eigenvectors, and verify `A @ v ≈ λ v`.

In [181]:
# Define matrix
A = np.array([[2, 1],
              [1, 2]])

# Compute eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(A)

print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)

# Verify A @ v ≈ λ v for each eigenvector
for i in range(len(eigvals)):
    lhs = A @ eigvecs[:, i]   # left-hand side
    rhs = eigvals[i] * eigvecs[:, i]  # right-hand side
    print(f"\nCheck for eigenvalue {eigvals[i]}:")
    print("A @ v:", lhs)
    print("λ v  :", rhs)
    print("Difference:", lhs - rhs)


Eigenvalues: [3. 1.]
Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Check for eigenvalue 3.0:
A @ v: [2.12132034 2.12132034]
λ v  : [2.12132034 2.12132034]
Difference: [0. 0.]

Check for eigenvalue 1.0:
A @ v: [-0.70710678  0.70710678]
λ v  : [-0.70710678  0.70710678]
Difference: [0. 0.]


**7.4** Solve the linear system `3x + 2y = 7` and `2x + 5y = 8`.

In [182]:
# Coefficient matrix
A = np.array([[3, 2],
              [2, 5]])

# Right-hand side vector  
b = np.array([7, 8])

# Solve the system.Here using Cramer’s rule in background
solution = np.linalg.solve(A, b)

print("Solution [x, y]:", solution)


Solution [x, y]: [1.72727273 0.90909091]


**7.5** Create a random 4×4 matrix and compute its **rank**.

In [19]:
# Set random seed for reproducibility
np.random.seed(123)

# Create a random 4x4 matrix
A = np.random.rand(4, 4)

# Compute its rank
rank_A = np.linalg.matrix_rank(A)

print("Random 4x4 matrix:\n", A)
print("Rank of the matrix:", rank_A)


Random 4x4 matrix:
 [[0.69646919 0.28613933 0.22685145 0.55131477]
 [0.71946897 0.42310646 0.9807642  0.68482974]
 [0.4809319  0.39211752 0.34317802 0.72904971]
 [0.43857224 0.0596779  0.39804426 0.73799541]]
Rank of the matrix: 4


**7.6** Perform QR decomposition of a random 4×3 matrix and verify `Q @ R ≈ A`.

In [185]:
# Set random seed 
np.random.seed(123)

# Create a random 4x3 matrix
A = np.random.rand(4, 3)

# Perform QR decomposition
Q, R = np.linalg.qr(A)

# Verify that Q @ R ≈ A
reconstructed = Q @ R

print("Original matrix A:\n", A)
print("\nQ matrix:\n", Q)
print("\nR matrix:\n", R)
print("\nReconstructed A (Q @ R):\n", reconstructed)
print("\nDifference A - Q@R:\n", A - reconstructed)


Original matrix A:
 [[0.69646919 0.28613933 0.22685145]
 [0.55131477 0.71946897 0.42310646]
 [0.9807642  0.68482974 0.4809319 ]
 [0.39211752 0.34317802 0.72904971]]

Q matrix:
 [[-0.5046518   0.57730224 -0.086298  ]
 [-0.39947494 -0.79903521 -0.24830641]
 [-0.71064797  0.09473082 -0.17824436]
 [-0.28412285 -0.1388918   0.9482223 ]]

R matrix:
 [[-1.3800985  -1.01598814 -0.83241438]
 [ 0.         -0.39248229 -0.26281506]
 [ 0.          0.          0.48094092]]

Reconstructed A (Q @ R):
 [[0.69646919 0.28613933 0.22685145]
 [0.55131477 0.71946897 0.42310646]
 [0.9807642  0.68482974 0.4809319 ]
 [0.39211752 0.34317802 0.72904971]]

Difference A - Q@R:
 [[2.22044605e-16 3.88578059e-16 4.16333634e-16]
 [0.00000000e+00 0.00000000e+00 1.66533454e-16]
 [1.11022302e-16 1.11022302e-16 1.11022302e-16]
 [0.00000000e+00 0.00000000e+00 1.11022302e-16]]


## 8) Reshaping, Stacking & Splitting

**8.1** Create `a = np.arange(24)` and reshape to (4,6).

In [187]:
# Create array from 0 to 23
a = np.arange(24)

# Reshape to 4x6
a_reshaped = a.reshape(4, 6)

print("Original array:\n", a)
print("\nReshaped array (4x6):\n", a_reshaped)


Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Reshaped array (4x6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


**8.2** From the (4,6) array, extract a (2,3) block from the center.

In [188]:
# Original 4x6 array
a = np.arange(24).reshape(4,6)

# Extract the center 2x3 block
center_block = a[1:3, 1:4]  # rows 1-2, columns 1-3

print("Original array (4x6):\n", a)
print("\nCenter 2x3 block:\n", center_block)


Original array (4x6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

Center 2x3 block:
 [[ 7  8  9]
 [13 14 15]]


**8.3** Vertically stack two arrays of shape (2,3) to obtain (4,3); then horizontally stack to obtain (2,6).

In [191]:
# Create two 2x3 arrays
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8, 9],
              [10, 11, 12]])

# Vertically stack: result shape (4,3)
V_stack = np.vstack((A, B))
print("Vertically stacked (4x3):\n", V_stack)

# Horizontally stack: result shape (2,6)
H_stack = np.hstack((A, B))
print("\nHorizontally stacked (2x6):\n", H_stack)


Vertically stacked (4x3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Horizontally stacked (2x6):
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


**8.4** Split an array of length 20 into 4 equal parts; then split into parts of lengths `[3,5,12]`.

In [23]:
import numpy as np

arr = np.arange(20)

parts_equal = np.array_split(arr, 4)
parts_equal

#np.array_split:
#Works even if the array length isn’t exactly divisible by the number of parts.
#Handles unequal lengths cleanly without extra calculations.

lengths = [3, 5, 12]
parts_custom = np.array_split(arr, np.cumsum(lengths)[:-1])
parts_custom


[array([0, 1, 2]),
 array([3, 4, 5, 6, 7]),
 array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])]

**8.5** Use `np.concatenate` to combine three arrays along axis 0 and along axis 1 (where shapes allow).

In [25]:
# Create three arrays
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
C = np.array([[9, 10],
              [11, 12]])

# Concatenate along axis 0 (rows)
concat_axis0 = np.concatenate((A, B, C), axis=0)
print("Concatenate along axis 0:\n", concat_axis0)

# Concatenate along axis 1 (columns)
concat_axis1 = np.concatenate((A, B, C), axis=1)
print("\nConcatenate along axis 1:\n", concat_axis1)


Concatenate along axis 0:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

Concatenate along axis 1:
 [[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


## 9) Real‑World Mini Case Studies

**9.1 Finance**: Prices of a stock for 10 days are `p = [100, 102, 101, 103, 105, 104, 106, 107, 110, 108]`. Compute **daily returns** (percentage) and **cumulative return**.

In [43]:
p = np.array([100, 102, 101, 103, 105, 104, 106, 107, 110, 108])
daily_returns = (p[1:] - p[:-1]) / p[:-1] * 100
print("Daily returns (%):", daily_returns)
cumulative_return = (p[-1] - p[0]) / p[0] * 100
print("Cumulative return (%):", cumulative_return)


Daily returns (%): [ 2.         -0.98039216  1.98019802  1.94174757 -0.95238095  1.92307692
  0.94339623  2.80373832 -1.81818182]
Cumulative return (%): 8.0


**9.2 Demography**: Ages of 20 people are in an array. Compute mean, median, std, and the proportion aged 18–30. *(Generate random integers 10–80 with a fixed seed.)*

In [198]:
# Set random seed 
np.random.seed(42)

# Generate ages of 20 people between 10 and 80
ages = np.random.randint(10, 81, size=20)
print("Ages:", ages)

# 1️⃣ Compute mean
mean_age = np.mean(ages)

# 2️⃣ Compute median
median_age = np.median(ages)

# 3️⃣ Compute standard deviation
std_age = np.std(ages)

# 4️⃣ Compute proportion aged 18–30
proportion_18_30 = np.sum((ages >= 18) & (ages <= 30)) / len(ages)

# Print results
print("\nMean age:", mean_age)
print("Median age:", median_age)
print("Standard deviation:", std_age)
print("Proportion aged 18–30:", proportion_18_30)


Ages: [61 24 70 30 33 12 31 62 11 39 47 11 73 69 30 42 67 31 58 68]

Mean age: 43.45
Median age: 40.5
Standard deviation: 20.66512763086645
Proportion aged 18–30: 0.15


**9.3 Quality Control**: Simulate 1,000 measurements with true value 50 and measurement noise `N(0, 2^2)`. What fraction of measurements fall within ±3 of the true value?

In [47]:
# Set random seed
np.random.seed(42)

# True value and noise
true_value = 50
sigma = 2

# Generate 1000 measurements with Gaussian noise
measurements = true_value + np.random.normal(0, sigma, 1000)

# Compute fraction within ±3
within_tolerance = np.mean((measurements >= 47) & (measurements <= 53))

print("Fraction within ±3:", within_tolerance)


Fraction within ±3: 0.868


**9.4 A/B Testing**: Variant A converts 48/500 users; Variant B converts 62/500. Compute conversion rates and the **absolute lift** (B−A). Simulate 10,000 bootstrap samples of the lift.

In [48]:
# Observed conversions
conversions_A = 48
conversions_B = 62
n_A = 500
n_B = 500

# Conversion rates
rate_A = conversions_A / n_A
rate_B = conversions_B / n_B

# Absolute lift (B - A)
lift = rate_B - rate_A

print("Conversion rate A:", rate_A)
print("Conversion rate B:", rate_B)
print("Absolute lift (B-A):", lift)


Conversion rate A: 0.096
Conversion rate B: 0.124
Absolute lift (B-A): 0.027999999999999997


**9.5 Sports Analytics**: Given player scores over 8 games, compute moving average with window size 3 using vectorized operations (no loops). *(Generate random integers 0–30.)*

In [49]:
import numpy as np

# Set random seed for reproducibility
np.random.seed(42)

# Generate player scores for 8 games (0–30)
scores = np.random.randint(0, 31, size=8)
print("Scores:", scores)

# Option 1: Using np.convolve
window_size = 3
moving_avg = np.convolve(scores, np.ones(window_size)/window_size, mode='valid')
print("Moving average (window=3):", moving_avg)



Scores: [ 6 19 28 14 10  7 28 20]
Moving average (window=3): [17.66666667 20.33333333 17.33333333 10.33333333 15.         18.33333333]


**9.6 Image Mini‑Task**: Create a 10×10 grayscale image as a NumPy array with a white square (value 255) in the center and 0 elsewhere. Compute its mean pixel value.

In [50]:
# Create 10x10 image with all zeros (black)
img = np.zeros((10,10), dtype=np.uint8)

img[3:7, 3:7] = 255

mean_pixel = img.mean()
print("Mean pixel value:", mean_pixel)



Mean pixel value: 40.8


**9.7 Logistics**: There are 5 warehouses with inventories `[40, 55, 20, 80, 60]` and 4 stores with demands `[30, 50, 40, 35]`. Using NumPy (not loops), compute how many units remain after fulfilling demands sequentially from warehouses.

In [51]:
import numpy as np

# Inventories and demands
warehouses = np.array([40, 55, 20, 80, 60])
stores = np.array([30, 50, 40, 35])

# Compute cumulative inventories and demands
cum_inventory = np.cumsum(warehouses)
cum_demand = np.cumsum(stores)

# Remaining units after each store
remaining_after_each_store = cum_inventory[-1] - cum_demand
remaining_after_each_store = np.maximum(remaining_after_each_store, 0)

print("Remaining units after fulfilling demands sequentially:", remaining_after_each_store)


Remaining units after fulfilling demands sequentially: [225 175 135 100]
